### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by aldefouw**
We won't stay on 14.7.0 but we want this number to match the REDCap version.

### CODE REVIEW

**Comment by mmcev106** [comment]
@aldefouw, this makes sense.  However, as things are currently designed people will need to run a few steps on their local for this change to be reflected, correct?  Do you know what those steps are off the top of your head?  I'd like to consider automating them.

**Comment by aldefouw** [comment]
@mmcev106 - I would characterize this particular version as an "informational version" - it's really a cosmetic thing but I think it's also confusing to keep it out of sync with the REDCap version we're talking about.  

The `package.json` is necessary so that we can pull the features into redcap_cypress as a node module ... 

However, we aren't actually publishing these node modules officially with npm so this version referenced in the package.json files isn't used on a technical level.  Instead, we rely on the Git tags and branches to pull the correct version on the REDCap Cypress level.  

For example, on redcap_cypress you might have a package.json reference like this to pull in v14.7.0:
`"redcap_rsvc": "git://github.com/4bbakers/redcap_rsvc#v14.7.0"`

In this case, it's a reference to the branch name - but it can also reference a tag in some cases (like V13.1.37-ABC).  This is actually one of the aspects to keeping the branch name reflecting the REDCap version that I failed to articulate during today's RVP meeting but here's just one reason to keep it as is.

Also, I realized that the updates now include the shell script and feature .. might be better off just making this change directly on this repo instead.

**Comment by mmcev106** [comment]
@aldefouw, your changes look great.  I have two questions before merging this PR:

- I think [my question here](https://github.com/4bbakers/redcap_rsvc/pull/18#issuecomment-2460472123) should be addressed before I should approve this.
- It looks like something fishy happened when you merged the latest version of 4bbakers:v14.7.0 into aldefouw:v14.7.0.  It's including what looks like cherry picked versions of Theresa's latest commits (they have different hashes).  I need to resolve a merge conflict related to this same file on Mintoo's PR, so I'll really like to avoid re-doing that if possible.  Would it be possible to redo the last few commits of aldefouw:v14.7.0 such that what look like cherry-picked commits don't appear in the history?  I think it is important for us to use merge processes that don't introduce oddities like this, or we're going to have more conflicts in general.  If you'd prefer, I could take a crack at rebuilding the last few commits of aldefouw:v14.7.0.  I think it would only take me a few minutes.

**Comment by aldefouw** [comment]
@mmcev106  -  I made an adjustment to remove the merge commits.  Let me know if that fixed the issue you were seeing.  (I had to force push - which I prefer not doing - but those merge commits would have stuck around if I hadn't.)

As for your question, I will try to explain it in a different way than [here](https://github.com/4bbakers/redcap_rsvc/pull/18#issuecomment-2463385802).

The short answer is that the process is documented in the REDCap Cypress README: https://github.com/aldefouw/redcap_cypress?tab=readme-ov-file#rsvc-automated-feature-tests

It boils down to what tag or branch you point at for the `redcap_rsvc` repository in `package.json` on the redcap_cypress repository.

I'm all for automating processes, but we need to be careful how we implement this.

We need to able to: 

1) Run feature tests against a _**different**_ version of REDCap than is specified for `redcap_rsvc`
2) Run feature tests against the _**same**_ version of REDCap than is specified for `redcap_rsvc`

There are dozens of reasons to run the package against a different version than your REDCap version.  The most obvious is patch level version differences but for minor version differences we use the previous validated version as the initial regression test pass.

Whatever implementation is created needs a way for us to manually override a version difference.

**Comment by mmcev106** [comment]
@aldefouw, the odd merge issue & re-commits of Theresa's changes seem to be resolved.  Thank you!

It looks like we're having a pretty big miss on communicating about what existing "devs" should do to update their locals to reflect this change.  Could we discuss this over a quick call whenever you're available?

**Review by mmcev106 — APPROVED** [review]

**Pull request merged**
