### PR TITLE
Fixed some tests that were failing in the automated environment

### PR DESCRIPTION
**Pull request by schatto1**
Fixed the following tests:
- Feature Tests/A/Field Validation_8/A.4.8.0100. - Enable field validation.feature
- Feature Tests/A/File Repository_26/A.3.26.0100. - Public File Share.feature
- Feature Tests/A/Project Setup_4/A.6.4.0400. - Draft Mode.feature
- Feature Tests/B/Assign User Rights_6/B.2.6.100 - Basic Privileges.feature

Just creating this pull request to get stuff kicked off- actually waiting on [this](https://github.com/4bbakers/redcap_rsvc/pull/17) to be merged so I can clean up the conflict that'll be present in Feature Tests/A/Assign Administrators_3/A.2.3.0200. - Add Remove Admins.feature

### CODE REVIEW

**Comment by mmcev106** [comment]
@schatto1, thank you for this!  I'm just now seeing it.  Until we're ready to move this repo to Vanderbilt I won't get notifications for new PRs unless they're assigned to me.  PR #17 has been merged.  Let me know once the merge conflict is resolved, and I will review this.  Thanks again!

**Comment by schatto1** [comment]
@mmcev106, thanks for letting me know that Mintoo's PR was merged. I just merged it to this branch, so the pull request should be ready for review. Let me know if anything needs clarification or changes. Thanks again!

**Comment by mmcev106** [comment]
@schatto1, three of the features passed, but the following two failed:

- A.6.4.0400
- B.2.6.100

Do they succeed on your local?  Also, just FYI I added a minor commit to remove an extra line that I believe was introduced accidentally during the merge conflict.

**Comment by schatto1** [comment]
@mmcev106, thanks for the review and your commit.

For A.6.4.0400, I'm guessing that the test fails at finding the Choices text field when editing a field in the online designer? That's where it fails for me when using the upstream `redcap_cypress` repo and `rctf` packages.

I just created a pull request [#9](https://github.com/aldefouw/rctf/pull/9) in `rctf` with the changes that let that test pass. @aldefouw, when you have the change, could you review that PR and let me know what you think?

B.2.6.100 passes without issue for me on my local. @mmcev106, could you tell me where the test fails on your end?

**Comment by mmcev106** [comment]
@schatto1, I did a cypress run including your rctf PR prior to merging.  It looks there are [two failures on A.6.4.0400](https://cloud.cypress.io/projects/pvu79o/runs/1946/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22redcap_rsvc%2FFeature%20Tests%2FA%2FProject%20Setup_4%2FA.6.4.0400.%20-%20Draft%20Mode.feature%22%2C%22value%22%3A%22%5B%5C%22329bd777-6bef-4ce2-9755-10330fed4678%5C%22%5D%22%7D%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D).  Do you have any ideas as to the cause or what might be different on your local?

**Comment by schatto1** [comment]
@mmcev106, thanks for doing another cypress run on this. I wasn't entirely sure if PR [#10](https://github.com/aldefouw/rctf/pull/10) in RCTF was also needed but your error message confirms that that's another PR that's required for A.6.4.0400 to pass.

I'm still looking into why B.2.6.100 fails for you but passes for me. Thanks for your patience!

**Comment by mmcev106** [comment]
@schatto1, I'm still seeing [an error for A.6.4.0400](https://cloud.cypress.io/projects/pvu79o/runs/1949/test-results/2c90224d-f551-461d-98ae-dff648d59981?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22redcap_rsvc%2FFeature%20Tests%2FA%2FProject%20Setup_4%2FA.6.4.0400.%20-%20Draft%20Mode.feature%22%2C%22value%22%3A%22%5B%5C%22d47e5f17-8d86-4472-8180-f6af3dd6e2a3%5C%22%5D%22%7D%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D) after including both rctf PRs.

**Comment by mmcev106** [comment]
@schatto1, I believe the changes in the PR are all good.  Would it be helpful to go ahead and merge it, then create a new PR for any additional fixes for the failing features?

**Comment by schatto1** [comment]
@mmcev106, thanks for that suggestion- I think it does make sense to go ahead and merge it. Both A.6.4.0400 and B.2.6.100 are, I think, dependent on RCTF changes. I'll make a note of that in the swim lane tasks.

**Comment by schatto1** [comment]
@mmcev106, I just created PRs [#12](https://github.com/aldefouw/rctf/pull/12) and [#13](https://github.com/aldefouw/rctf/pull/13) in RCTF that should let B.2.6.100 pass once merged.

**Review by mmcev106 — APPROVED** [review]
Approving & merging.  A.6.4.0400 & B.2.6.100 are still failing, but are expected to be resolved by rctf changes instead of changes on this repo.

**Comment by mmcev106** [comment]
@schatto1, I've closed the issues for A.4.8.0100 & A.3.26.0100 as they're now passing.  [Cypress run 1956](https://cloud.cypress.io/projects/pvu79o/runs/1956/specs) includes both RCTF PRs, however A.6.4.0400 & B.2.6.100 are still failing.  Do you know if additional RCTF changes might be required?

**Pull request merged**
