### PR TITLE
Multiple features

### PR DESCRIPTION
**Pull request by alewis64**
This change was to the de-identification table export on line 132 of the script.

### CODE REVIEW

**Comment by mmcev106** [comment]
@alewis64, Adam D was working on A.3.30.0100 also, and each of your changes conflicted.  I went ahead and merged `4bbakers/v14.7.0` into `alewis64/adam_lewis` and resolved the merge conflict.  I think allowing his changes to override yours was the best course of action, but please let me know if you have any concerns about that.

**Comment by mmcev106** [comment]
I just renamed this PR since the name suggested a since feature and it actually contains changes for multiple features.  I also effectively merged the changes for B.5.21.0100. via #160, so that are no longer visible from this PR.

**Comment by alewis64** [comment]
> @alewis64, after fixing the merge conflict and merging #160 the only feature left in this PR is C.3.30.0200. I'm seeing [these failures](https://cloud.cypress.io/projects/pvu79o/runs/1956/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22redcap_rsvc%2FFeature%20Tests%2FC%2FRandomization_30%2FC.3.30.0200.%20Randomization%20project%20enable.feature%22%2C%22value%22%3A%22%5B%5C%2243d6ea8a-b754-4891-85ca-ca247d704242%5C%22%5D%22%7D%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D) on this feature. Are you seeing different behavior locally?

@mmcev106 
Yes I am seeing similar results. I fee like I may have fixed some of these last week and never put together a pull request, but it sounds like these may have been removed when the conflict happened. I will refresh my local and continue to work on this. 
image

**Comment by mmcev106** [comment]
@alewis64, the changes from my merge commit that included conflicts on A.3.30.0100 can be seen [here](https://github.com/alewis64/redcap_rsvc/commit/65d825cc2a779b6025847400df66d24854098c07).  I don't believe I overwrote any significant changes of yours while resolving the conflict...  If you're confident you committed changes at some point that you're not seeing, I might be able to help you retrieve them on your local.

**Comment by mmcev106** [comment]
@alewis64 & I just talked about this on a call.  The changes he was looking for are here in the PR, he just wasn't seeing them on this local.  We suspect cypress might have needed to be refreshed on his local after switching branches to see them.  Regardless, he's he's able to pick up where he left off.

**Pull request closed without merging**
